import bcrypt from "bcryptjs";

export interface MockStore {
  adminUser: any[];
  adminPasswordReset: any[];
  product: any[];
  productVariation: any[];
  category: any[];
  collection: any[];
  order: any[];
  inquiry: any[];
  blogPost: any[];
  review: any[];
  certificate: any[];
  heroSlide: any[];
  homepageSection: any[];
  video: any[];
  navigationMenu: any[];
  siteSetting: any[];
  mediaAsset: any[];
}

const defaultAdminPassword = bcrypt.hashSync(process.env.ADMIN_PASS || "admin123", 10);

const initialCategories = [
  {
    id: "cat-1",
    name: "Gaming Laptops",
    slug: "gaming-laptops",
    description: "High-performance laptops for gaming and streaming.",
    image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=800&auto=format&fit=crop",
    order: 1,
    featured: true,
    seoTitle: "Gaming Laptops – MM Laptop Center",
    seoDescription: "Shop high performance gaming laptops with RTX graphics.",
    productIds: "[]",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat-2",
    name: "Business Laptops",
    slug: "business-laptops",
    description: "Reliable laptops for professionals and enterprise.",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=800&auto=format&fit=crop",
    order: 2,
    featured: true,
    seoTitle: "Business Laptops – MM Laptop Center",
    seoDescription: "Shop business ultrabooks and work laptops.",
    productIds: "[]",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat-3",
    name: "Ultrabooks",
    slug: "ultrabooks",
    description: "Ultra-light laptops with all-day battery life.",
    image: "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?q=80&w=800&auto=format&fit=crop",
    order: 3,
    featured: true,
    seoTitle: "Ultrabooks – MM Laptop Center",
    seoDescription: "Ultra-thin, light machines for productivity on the move.",
    productIds: "[]",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat-4",
    name: "Budget Laptops",
    slug: "budget-laptops",
    description: "Affordable laptops for everyday computing.",
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?q=80&w=800&auto=format&fit=crop",
    order: 4,
    featured: false,
    seoTitle: "Budget Laptops – MM Laptop Center",
    seoDescription: "Affordable reliable laptops.",
    productIds: "[]",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat-5",
    name: "Accessories",
    slug: "accessories",
    description: "Essential laptop accessories and peripherals.",
    image: "https://images.unsplash.com/photo-1547082299-de196ea013d6?q=80&w=800&auto=format&fit=crop",
    order: 5,
    featured: true,
    seoTitle: "Laptop Accessories – MM Laptop Center",
    seoDescription: "Bags, docks, chargers, and keyboards.",
    productIds: "[]",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat-6",
    name: "Monitors",
    slug: "monitors",
    description: "External displays for work and gaming.",
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=800&auto=format&fit=crop",
    order: 6,
    featured: false,
    seoTitle: "Monitors – MM Laptop Center",
    seoDescription: "High refresh rate and 4K displays.",
    productIds: "[]",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat-7",
    name: "Keyboards",
    slug: "keyboards",
    description: "Mechanical and wireless keyboards.",
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=800&auto=format&fit=crop",
    order: 7,
    featured: false,
    seoTitle: "Keyboards – MM Laptop Center",
    seoDescription: "Mechanical RGB keyboards and wireless options.",
    productIds: "[]",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat-8",
    name: "Mice",
    slug: "mice",
    description: "Precision mice for gaming and productivity.",
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?q=80&w=800&auto=format&fit=crop",
    order: 8,
    featured: false,
    seoTitle: "Mice – MM Laptop Center",
    seoDescription: "Gaming and ergonomic mice.",
    productIds: "[]",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat-9",
    name: "Bags",
    slug: "bags",
    description: "Laptop bags, sleeves, and backpacks.",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=800&auto=format&fit=crop",
    order: 9,
    featured: false,
    seoTitle: "Laptop Bags – MM Laptop Center",
    seoDescription: "Water resistant laptop backpacks and sleeves.",
    productIds: "[]",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

const initialProducts = [
  {
    id: "prod-1",
    handle: "asus-rog-strix-g16",
    title: "ASUS ROG Strix G16",
    categoryId: "cat-1",
    price: 365000,
    compareAtPrice: 395000,
    description: "16-inch FHD 165Hz, RTX 4060, Intel i7-13650HX, 16GB RAM, 512GB SSD. High performance gaming powerhouse with liquid metal cooling.",
    descriptionHtml: "<p>16-inch FHD 165Hz, RTX 4060, Intel i7-13650HX, 16GB RAM, 512GB SSD.</p>",
    sku: "ROG-G16-4060",
    inventory: 15,
    availableForSale: true,
    status: "ACTIVE",
    featuredImage: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=800&auto=format&fit=crop",
    images: JSON.stringify(["https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=800&auto=format&fit=crop"]),
    productType: "gaming-laptops",
    vendor: "MM Laptop Center",
    tags: JSON.stringify(["laptop", "gaming", "asus", "rtx4060"]),
    collectionIds: JSON.stringify(["col-1", "col-3"]),
    isFeatured: true,
    displayOrder: 1,
    color: "Eclipse Gray",
    ram: "16GB",
    storage: "512GB SSD",
    processor: "Intel Core i7-13650HX",
    condition: "Brand New",
    seoTitle: "ASUS ROG Strix G16 – MM Laptop Center",
    seoDescription: "Shop ASUS ROG Strix G16 Gaming Laptop with RTX 4060.",
    specifications: {},
    customAttributes: {},
    createdAt: new Date(),
    updatedAt: new Date(),
    variations: [],
  },
  {
    id: "prod-2",
    handle: "dell-xps-15",
    title: "Dell XPS 15 (9530)",
    categoryId: "cat-2",
    price: 450000,
    compareAtPrice: 485000,
    description: "15.6-inch 3.5K OLED InfinityEdge, Intel Core i9-13900H, 32GB DDR5 RAM, 1TB NVMe SSD, NVIDIA RTX 4070. Precision CNC aluminum chassis.",
    descriptionHtml: "<p>15.6-inch OLED, Intel i9, 32GB RAM, 1TB SSD, premium build</p>",
    sku: "DELL-XPS-15-OLED",
    inventory: 10,
    availableForSale: true,
    status: "ACTIVE",
    featuredImage: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?q=80&w=800&auto=format&fit=crop",
    images: JSON.stringify(["https://images.unsplash.com/photo-1593642632823-8f785ba67e45?q=80&w=800&auto=format&fit=crop"]),
    productType: "business-laptops",
    vendor: "MM Laptop Center",
    tags: JSON.stringify(["laptop", "business", "dell", "oled"]),
    collectionIds: JSON.stringify(["col-1", "col-4"]),
    isFeatured: true,
    displayOrder: 2,
    color: "Platinum Silver",
    ram: "32GB",
    storage: "1TB SSD",
    processor: "Intel Core i9-13900H",
    condition: "Brand New",
    seoTitle: "Dell XPS 15 – MM Laptop Center",
    seoDescription: "Dell XPS 15 OLED Touch laptop for creators and executives.",
    specifications: {},
    customAttributes: {},
    createdAt: new Date(),
    updatedAt: new Date(),
    variations: [],
  },
  {
    id: "prod-3",
    handle: "lenovo-thinkpad-x1-carbon",
    title: "Lenovo ThinkPad X1 Carbon Gen 11",
    categoryId: "cat-3",
    price: 335000,
    compareAtPrice: 360000,
    description: "14-inch WUXGA IPS anti-glare, Intel Core i7-1355U, 16GB LPDDR5, 512GB SSD, ultra-light 1.12kg carbon fiber chassis with legendary keyboard.",
    descriptionHtml: "<p>14-inch IPS, Intel i7, 16GB RAM, 512GB SSD, ultra-light 1.12kg</p>",
    sku: "THINKPAD-X1-G11",
    inventory: 12,
    availableForSale: true,
    status: "ACTIVE",
    featuredImage: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?q=80&w=800&auto=format&fit=crop",
    images: JSON.stringify(["https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?q=80&w=800&auto=format&fit=crop"]),
    productType: "ultrabooks",
    vendor: "MM Laptop Center",
    tags: JSON.stringify(["laptop", "ultrabook", "lenovo", "thinkpad"]),
    collectionIds: JSON.stringify(["col-2", "col-4"]),
    isFeatured: true,
    displayOrder: 3,
    color: "Deep Black",
    ram: "16GB",
    storage: "512GB SSD",
    processor: "Intel Core i7-1355U",
    condition: "Brand New",
    seoTitle: "Lenovo ThinkPad X1 Carbon Gen 11 – MM Laptop Center",
    seoDescription: "Lenovo ThinkPad X1 Carbon business flagship laptop.",
    specifications: {},
    customAttributes: {},
    createdAt: new Date(),
    updatedAt: new Date(),
    variations: [],
  },
  {
    id: "prod-4",
    handle: "apple-macbook-air-m2",
    title: "Apple MacBook Air 13.6\" (M2 Chip)",
    categoryId: "cat-3",
    price: 295000,
    compareAtPrice: 320000,
    description: "13.6-inch Liquid Retina display, Apple M2 8-core CPU / 8-core GPU, 8GB unified memory, 256GB SSD, MagSafe 3 charging, 18-hour battery.",
    descriptionHtml: "<p>13.6-inch Liquid Retina, Apple M2, 8GB RAM, 256GB SSD, 18hr battery</p>",
    sku: "MBA-M2-13",
    inventory: 18,
    availableForSale: true,
    status: "ACTIVE",
    featuredImage: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=800&auto=format&fit=crop",
    images: JSON.stringify(["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=800&auto=format&fit=crop"]),
    productType: "ultrabooks",
    vendor: "MM Laptop Center",
    tags: JSON.stringify(["macbook", "apple", "m2", "ultrabook"]),
    collectionIds: JSON.stringify(["col-1", "col-2"]),
    isFeatured: true,
    displayOrder: 4,
    color: "Midnight",
    ram: "8GB Unified",
    storage: "256GB SSD",
    processor: "Apple M2 Chip",
    condition: "Brand New",
    seoTitle: "Apple MacBook Air M2 – MM Laptop Center",
    seoDescription: "Apple MacBook Air M2 Chip in Midnight, Starlight, and Space Gray.",
    specifications: {},
    customAttributes: {},
    createdAt: new Date(),
    updatedAt: new Date(),
    variations: [],
  },
  {
    id: "prod-5",
    handle: "hp-pavilion-15",
    title: "HP Pavilion 15",
    categoryId: "cat-4",
    price: 165000,
    compareAtPrice: 185000,
    description: "15.6-inch FHD micro-edge, AMD Ryzen 5 7530U 6-core processor, 8GB DDR4 RAM, 256GB PCIe NVMe SSD, fast charge battery.",
    descriptionHtml: "<p>15.6-inch FHD, AMD Ryzen 5, 8GB RAM, 256GB SSD</p>",
    sku: "HP-PAV-15-R5",
    inventory: 25,
    availableForSale: true,
    status: "ACTIVE",
    featuredImage: "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?q=80&w=800&auto=format&fit=crop",
    images: JSON.stringify(["https://images.unsplash.com/photo-1541807084-5c52b6b3adef?q=80&w=800&auto=format&fit=crop"]),
    productType: "budget-laptops",
    vendor: "MM Laptop Center",
    tags: JSON.stringify(["laptop", "budget", "hp", "ryzen"]),
    collectionIds: JSON.stringify(["col-2"]),
    isFeatured: true,
    displayOrder: 5,
    color: "Natural Silver",
    ram: "8GB",
    storage: "256GB SSD",
    processor: "AMD Ryzen 5 7530U",
    condition: "Brand New",
    seoTitle: "HP Pavilion 15 – MM Laptop Center",
    seoDescription: "Affordable HP Pavilion 15 for students and home use.",
    specifications: {},
    customAttributes: {},
    createdAt: new Date(),
    updatedAt: new Date(),
    variations: [],
  },
  {
    id: "prod-6",
    handle: "msi-katana-15",
    title: "MSI Katana 15 B13V",
    categoryId: "cat-1",
    price: 275000,
    compareAtPrice: 310000,
    description: "15.6-inch FHD 144Hz IPS display, Intel Core i7-13620H, NVIDIA GeForce RTX 4050 6GB, 16GB DDR5 RAM, 512GB NVMe SSD, 4-Zone RGB keyboard.",
    descriptionHtml: "<p>15.6-inch FHD 144Hz, RTX 4050, Intel i7, 16GB RAM, 512GB SSD</p>",
    sku: "MSI-KATANA-15",
    inventory: 14,
    availableForSale: true,
    status: "ACTIVE",
    featuredImage: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=800&auto=format&fit=crop",
    images: JSON.stringify(["https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=800&auto=format&fit=crop"]),
    productType: "gaming-laptops",
    vendor: "MM Laptop Center",
    tags: JSON.stringify(["laptop", "gaming", "msi", "rtx4050"]),
    collectionIds: JSON.stringify(["col-3"]),
    isFeatured: true,
    displayOrder: 6,
    color: "Black",
    ram: "16GB DDR5",
    storage: "512GB SSD",
    processor: "Intel Core i7-13620H",
    condition: "Brand New",
    seoTitle: "MSI Katana 15 – MM Laptop Center",
    seoDescription: "MSI Katana 15 gaming laptop with high refresh display and RTX 4050.",
    specifications: {},
    customAttributes: {},
    createdAt: new Date(),
    updatedAt: new Date(),
    variations: [],
  },
  {
    id: "prod-7",
    handle: "logitech-mx-master-3s",
    title: "Logitech MX Master 3S Wireless Mouse",
    categoryId: "cat-8",
    price: 28000,
    compareAtPrice: 32000,
    description: "Quiet clicks with 8K DPI any-surface tracking, MagSpeed electromagnetic scrolling, USB-C fast charging, Bluetooth & Logi Bolt receiver.",
    descriptionHtml: "<p>Wireless ergonomic mouse with 8K DPI sensor and quiet clicks</p>",
    sku: "LOGI-MX3S-GR",
    inventory: 40,
    availableForSale: true,
    status: "ACTIVE",
    featuredImage: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?q=80&w=800&auto=format&fit=crop",
    images: JSON.stringify(["https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?q=80&w=800&auto=format&fit=crop"]),
    productType: "mice",
    vendor: "MM Laptop Center",
    tags: JSON.stringify(["accessories", "mouse", "logitech"]),
    collectionIds: JSON.stringify(["col-1", "col-4"]),
    isFeatured: true,
    displayOrder: 7,
    color: "Graphite",
    condition: "Brand New",
    seoTitle: "Logitech MX Master 3S – MM Laptop Center",
    seoDescription: "Logitech MX Master 3S wireless performance mouse.",
    specifications: {},
    customAttributes: {},
    createdAt: new Date(),
    updatedAt: new Date(),
    variations: [],
  },
  {
    id: "prod-8",
    handle: "dell-27-monitor-s2721d",
    title: "Dell 27\" 4K UHD Monitor (S2721QS)",
    categoryId: "cat-6",
    price: 98000,
    compareAtPrice: 110000,
    description: "27-inch 4K UHD 3840x2160 IPS display, AMD FreeSync, HDR support, height-adjustable stand, dual HDMI & DisplayPort.",
    descriptionHtml: "<p>27-inch 4K UHD IPS display with USB-C connectivity</p>",
    sku: "DELL-S2721QS",
    inventory: 22,
    availableForSale: true,
    status: "ACTIVE",
    featuredImage: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=800&auto=format&fit=crop",
    images: JSON.stringify(["https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=800&auto=format&fit=crop"]),
    productType: "monitors",
    vendor: "MM Laptop Center",
    tags: JSON.stringify(["monitor", "dell", "4k", "display"]),
    collectionIds: JSON.stringify(["col-1", "col-4"]),
    isFeatured: true,
    displayOrder: 8,
    color: "Silver",
    condition: "Brand New",
    seoTitle: "Dell 27\" 4K Monitor – MM Laptop Center",
    seoDescription: "Crisp 4K UHD Dell monitor for productivity and entertainment.",
    specifications: {},
    customAttributes: {},
    createdAt: new Date(),
    updatedAt: new Date(),
    variations: [],
  },
];

const initialCollections = [
  {
    id: "col-1",
    handle: "hot-deals",
    title: "Hot Deals",
    description: "Limited-time discounts on top laptops, ultrabooks, and accessories.",
    descriptionHtml: "<p>Limited-time discounts on top laptops and accessories.</p>",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=800&auto=format&fit=crop",
    isFeatured: true,
    productHandles: JSON.stringify(["asus-rog-strix-g16", "dell-xps-15", "apple-macbook-air-m2", "logitech-mx-master-3s"]),
    seoTitle: "Hot Deals – MM Laptop Center",
    seoDescription: "Save big on the best laptops and peripherals in Pakistan.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "col-2",
    handle: "new-arrivals",
    title: "New Arrivals",
    description: "The latest laptops, gaming rigs, and tech just landed in store.",
    descriptionHtml: "<p>The latest laptops and tech just landed in store.</p>",
    image: "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?q=80&w=800&auto=format&fit=crop",
    isFeatured: true,
    productHandles: JSON.stringify(["apple-macbook-air-m2", "lenovo-thinkpad-x1-carbon", "hp-pavilion-15"]),
    seoTitle: "New Arrivals – MM Laptop Center",
    seoDescription: "Check out the newest laptops in stock.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "col-3",
    handle: "gaming-setup",
    title: "Gaming Setup",
    description: "Build your ultimate battle station with our curated laptops and accessories.",
    descriptionHtml: "<p>Build your ultimate gaming rig with our curated picks.</p>",
    image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=800&auto=format&fit=crop",
    isFeatured: true,
    productHandles: JSON.stringify(["asus-rog-strix-g16", "msi-katana-15"]),
    seoTitle: "Gaming Setup – MM Laptop Center",
    seoDescription: "High refresh rate and RTX gaming laptops.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "col-4",
    handle: "work-from-home",
    title: "Work From Home",
    description: "Everything you need for a productive home office setup.",
    descriptionHtml: "<p>Everything you need for a productive home office.</p>",
    image: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?q=80&w=800&auto=format&fit=crop",
    isFeatured: false,
    productHandles: JSON.stringify(["dell-xps-15", "lenovo-thinkpad-x1-carbon", "dell-27-monitor-s2721d", "logitech-mx-master-3s"]),
    seoTitle: "Work From Home – MM Laptop Center",
    seoDescription: "Reliable business laptops, monitors, and peripherals.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

const initialHeroSlides = [
  {
    id: "slide-1",
    imageUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=2070&auto=format&fit=crop",
    mobileImageUrl: null,
    imageAlt: "Premium laptop on a desk",
    eyebrow: "Your Trusted Tech Destination",
    title: "Premium Laptops",
    titleHighlight: "& Tech",
    description: "Discover the latest gaming laptops, business ultrabooks, and budget-friendly machines — all backed by genuine warranty.",
    ctaPrimaryLabel: "Shop Now",
    ctaPrimaryHref: "/products",
    ctaSecondaryLabel: "View Deals",
    ctaSecondaryHref: "/collections/hot-deals",
    isActive: true,
    order: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "slide-2",
    imageUrl: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=1974&auto=format&fit=crop",
    mobileImageUrl: null,
    imageAlt: "Gaming laptop with RGB keyboard",
    eyebrow: "Gaming Laptops",
    title: "Dominate",
    titleHighlight: "Every Game",
    description: "High-refresh displays, the latest NVIDIA GPUs, and powerful processors — built for gamers who demand the best.",
    ctaPrimaryLabel: "Shop Gaming",
    ctaPrimaryHref: "/collections/gaming-setup",
    ctaSecondaryLabel: "Compare Specs",
    ctaSecondaryHref: "/compare",
    isActive: true,
    order: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "slide-3",
    imageUrl: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?q=80&w=2070&auto=format&fit=crop",
    mobileImageUrl: null,
    imageAlt: "Person working on an ultrabook in a modern office",
    eyebrow: "Business & Ultrabooks",
    title: "Work Smarter,",
    titleHighlight: "Anywhere",
    description: "Lightweight, all-day battery laptops designed for professionals who need reliability on the go.",
    ctaPrimaryLabel: "Shop Business",
    ctaPrimaryHref: "/collections/work-from-home",
    ctaSecondaryLabel: "Contact Sales",
    ctaSecondaryHref: "/contact",
    isActive: true,
    order: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

const initialReviews = [
  {
    id: "rev-1",
    authorName: "Ahmed K.",
    authorEmail: "ahmed@example.com",
    authorImage: null,
    rating: 5,
    content: "Bought the ASUS ROG Strix G16 – runs every game smoothly. Fast delivery to Islamabad and authentic warranty!",
    productId: "prod-1",
    productHandle: "asus-rog-strix-g16",
    isFeatured: true,
    status: "approved",
    isVerifiedPurchase: true,
    helpfulCount: 14,
    images: "[]",
    adminNote: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "rev-2",
    authorName: "Sara M.",
    authorEmail: "sara@example.com",
    authorImage: null,
    rating: 5,
    content: "My Dell XPS 15 arrived in immaculate condition. The OLED display is out of this world for video editing.",
    productId: "prod-2",
    productHandle: "dell-xps-15",
    isFeatured: true,
    status: "approved",
    isVerifiedPurchase: true,
    helpfulCount: 9,
    images: "[]",
    adminNote: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "rev-3",
    authorName: "Usman R.",
    authorEmail: "usman@example.com",
    authorImage: null,
    rating: 5,
    content: "Best laptop shop in Pakistan. Excellent guidance on WhatsApp and prompt dispatch. Highly recommended!",
    productId: null,
    productHandle: null,
    isFeatured: true,
    status: "approved",
    isVerifiedPurchase: true,
    helpfulCount: 22,
    images: "[]",
    adminNote: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

const initialCertificates = [
  {
    id: "cert-1",
    name: "Authorized Dealer",
    image: "https://placehold.co/200x200?text=Authorized",
    description: "Official authorized dealer for major laptop brands.",
    order: 1,
    isActive: true,
    isVerifiedBy: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cert-2",
    name: "Genuine Products",
    image: "https://placehold.co/200x200?text=Genuine",
    description: "100% authentic products with manufacturer warranty.",
    order: 2,
    isActive: true,
    isVerifiedBy: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cert-3",
    name: "Warranty Support",
    image: "https://placehold.co/200x200?text=Warranty",
    description: "Full warranty support on all laptops and accessories.",
    order: 3,
    isActive: true,
    isVerifiedBy: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cert-4",
    name: "Secure Checkout",
    image: "https://placehold.co/200x200?text=Secure",
    description: "Safe and secure payment processing & Cash on Delivery.",
    order: 4,
    isActive: true,
    isVerifiedBy: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

const initialBlogPosts = [
  {
    id: "blog-1",
    title: "How to Choose the Right Gaming Laptop in 2026",
    slug: "choose-gaming-laptop-2026",
    excerpt: "GPU, refresh rate, cooling – everything you need to know before buying a gaming laptop in Pakistan.",
    content: "<p>Gaming laptops have evolved rapidly with newer RTX 40-series cards and DDR5 RAM. Here is our comprehensive guide to picking the perfect machine for your budget and competitive gaming needs.</p>",
    featuredImage: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=800&auto=format&fit=crop",
    categoryId: "cat-1",
    author: "Mudassir Meer",
    status: "published",
    isFeatured: true,
    publishedAt: new Date(),
    seoTitle: "How to Choose the Right Gaming Laptop in 2026",
    seoDescription: "Gaming laptop buying guide for gamers in Pakistan.",
    tags: JSON.stringify(["gaming", "guide", "laptops"]),
    views: 342,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "blog-2",
    title: "Top 5 Business Laptops for Remote Work and Travel",
    slug: "top-business-laptops-remote-work",
    excerpt: "Our top picks for the most reliable business laptops that keep you productive and connected anywhere.",
    content: "<p>Remote work demands reliability, robust security, and all-day battery life. These business laptops deliver premium build quality, crisp keyboards, and high performance.</p>",
    featuredImage: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=800&auto=format&fit=crop",
    categoryId: "cat-2",
    author: "MM Laptop Center",
    status: "published",
    isFeatured: true,
    publishedAt: new Date(),
    seoTitle: "Top 5 Business Laptops for Remote Work",
    seoDescription: "Best business laptops for work from home and enterprise.",
    tags: JSON.stringify(["business", "remote-work", "ultrabook"]),
    views: 215,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

const initialSiteSettings = [
  {
    id: "set-1",
    key: "siteName",
    value: "MM Laptop Center",
    updatedAt: new Date(),
  },
  {
    id: "set-2",
    key: "termsOfService",
    value: {
      title: "Terms and Conditions",
      body: "<p>Welcome to MM Laptop Center. These terms and conditions outline the rules and regulations for the purchase of laptops and tech accessories.</p>",
    },
    updatedAt: new Date(),
  },
  {
    id: "set-3",
    key: "privacyPolicy",
    value: {
      title: "Privacy Policy",
      body: "<p>At MM Laptop Center, we respect and safeguard the personal data of our customers across Pakistan.</p>",
    },
    updatedAt: new Date(),
  },
  {
    id: "set-4",
    key: "refundPolicy",
    value: {
      title: "Warranty & Return Policy",
      body: "<p>All laptops sold by MM Laptop Center are backed by official warranty. Contact our support team within 7 days for any claims or queries.</p>",
    },
    updatedAt: new Date(),
  },
];

const initialNavigationMenu = [
  {
    id: "nav-header",
    location: "header",
    items: [
      { text: "Home", href: "/" },
      { text: "Laptops", href: "/products" },
      { text: "Categories", href: "/category/gaming-laptops" },
      { text: "Deals", href: "/collections/hot-deals" },
      { text: "About", href: "/about-us" },
      { text: "Contact", href: "/contact" },
    ],
    updatedAt: new Date(),
  },
];

const initialAdminUsers = [
  {
    id: "admin-1",
    email: (process.env.ADMIN_USER ?? process.env.ADMIN_EMAIL ?? "info.mmlaptopcenter@gmail.com").toLowerCase().trim(),
    password: defaultAdminPassword,
    name: "MM Laptop Center Admin",
    createdAt: new Date(),
  },
];

const initialHomepageSection = [
  {
    id: "sec-1",
    sectionKey: "essence",
    title: "Your Trusted Tech Destination",
    subtitle: "Premium laptops and accessories for work, gaming, and everyday life in Pakistan.",
    content: [],
    order: 1,
    isActive: true,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=1400&auto=format&fit=crop",
    updatedAt: new Date(),
  },
];

export function createMockStore(): MockStore {
  return {
    adminUser: [...initialAdminUsers],
    adminPasswordReset: [],
    product: [...initialProducts],
    productVariation: [],
    category: [...initialCategories],
    collection: [...initialCollections],
    order: [],
    inquiry: [],
    blogPost: [...initialBlogPosts],
    review: [...initialReviews],
    certificate: [...initialCertificates],
    heroSlide: [...initialHeroSlides],
    homepageSection: [...initialHomepageSection],
    video: [],
    navigationMenu: [...initialNavigationMenu],
    siteSetting: [...initialSiteSettings],
    mediaAsset: [],
  };
}
